### ISSUE TITLE
Broken Docker images: zipped binaries and confused versions

### ISSUE THREAD

**Issue by paddycarey** [ngrok/docker-ngrok#13]
The Docker images currently on Docker Hub are broken and contain zipped files in place of binaries. Looks like it's been fixed in https://github.com/ngrok/docker-ngrok/pull/12 but not released. Do you know if new images will be released soon?

I've also noticed that the images pushed seem to have confused versions, e.g. if I run the current `ngrok/ngrok:2` image, and unzip the zipfile that's included at `/bin/ngrok`, it's actually version 3.0.2 rather than the expected version 2.x.

```
root@084ea878ed74:/# ./ngrok --version
ngrok version 3.0.2
```

**Comment by krwenholz** [comment]
Hi @paddycarey the v2 tags should be fixed. Mind verifying before I close this out?

Related, v3 is coming soon!

**Comment by paddycarey** [comment]
Looks good here, thank you!

**Comment by krwenholz** [comment]
Awesome. Thanks so much. Let us know if you run into any other trouble.
