### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by LeeThompson** [ngrok/docker-ngrok#15]
Today's update completely broke me, the container won't even run to allow me to update the config file.

**Comment by krwenholz** [comment]
Hi @LeeThompson can you let us know which tag you are using? We did update the `latest` tag to our new v3 and have found a few hiccups in there.

You were probably using a version that more closely matches the `2` tag. We'd suggest moving to that tag until you're ready for `latest` on our new `v3` agent. We're about to release some documentation for going through the upgrade.

**Comment by LeeThompson** [comment]
I'm on alpine

**Comment by krwenholz** [comment]
Ah yes. The `alpine` tag by itself will also track `latest`. We haven't upgraded in a long time. Apologies for the surprise here.

**Comment by LeeThompson** [comment]
Working with 2.3.40 alpine now.   The docs on the website seem to all be 2.x oriented too, I had no idea what it was so unhappy with.

**Comment by krwenholz** [comment]
Yeah those should be flipping shortly. Tough to coordinate. Thanks for your patience and please let us know if you have any more trouble! We're going to add some docs pointing to the v2->v3 upgrade guide on this README as well.

**Comment by LeeThompson** [comment]
Be sure to have notes for the docker image in the registry   With maybe a big bold 'be sure to do this before updating!' ;)

**Comment by krwenholz** [comment]
Thanks Lee!
