### ISSUE TITLE
Container Does Not Work For Scenarios Where The Container Is Not Started From Command Line

### ISSUE THREAD

**Issue by LeeThompson** [ngrok/docker-ngrok#3]
Set it up as indicated using the NGROK_CONFIG environment variable and it stops immediately with this:

`Incorrect Usage: flag provided but not defined: -config`

I took both environment variables out entirely NGROK_AUTHTOKEN and NGROK_CONFIG and the same error appears.

Basically `entrypoint.sh` is broken for ngrok/ngrok:latest (debian).

Just tried it alpine, same thing.

**Comment by LeeThompson** [comment]
I tried just running the container without any environment variables, it gives the same error.

Was this tested?

**Comment by LeeThompson** [comment]
I figured it out:

The entry point needs a command added to it:

`start -all`

So entrypoint.sh should be something like 

```
#!/bin/sh
CONFIGDIR="/var/lib/ngrok"
ARGS=""

# Set the authorization token.
if [ -n "$NGROK_AUTHTOKEN" ]; then
    cat > $CONFIGDIR/auth-config.yml <<EOF
    authtoken: $NGROK_AUTHTOKEN
EOF
    ARGS="$ARGS --config=$CONFIGDIR/auth-config.yml"
fi

# Set the config file location; make sure agent uses default config even if NGROK_AUTHTOKEN is set
if [ -n "$NGROK_CONFIG" ]; then
    ARGS="$ARGS --config=$NGROK_CONFIG"
else
    ARGS="--config=$CONFIGDIR/ngrok.yml $ARGS"
fi

exec ngrok "$@" start --all $ARGS
```

For those trying to get this to work the "`cmd`" field needs to be set to "`start --all`".
Unfortunately, I'm not using this on a system that uses docker-compose so I can't give the exact syntax.

**Comment by zach-sherman** [comment]
looking into this, thanks for providing so many details

**Comment by zach-sherman** [comment]
Are you trying to run it without passing a subcommand? It seems like what you want could be accomplished by calling the image with `start --all` passed as arguments. Unfortunately, adding `start --all` to the entrypoint would break the `docker run ngrok/ngrok http 80`-style use-case.

**Comment by LeeThompson** [comment]
Hmm I see that, could `entrypoint.sh` tell if nothing is passed in (as in the `http 80` use case) and then do `start --all`?

Alternately could have an `NGROK_START_ALL `environment variable, if set to true have `entrypoint.sh` add `start --all`

Worst case, could just add this to the documentation on dockerhub and the readme.md

**Comment by zach-sherman** [comment]
I think the former is the best option. Testing a solution now.

**Comment by zach-sherman** [comment]
Now released to docker hub.

**Comment by LeeThompson** [comment]
Awesome!
