### ISSUE TITLE
Add workaround for --net=host for mac and windows users

### ISSUE THREAD

**Issue by russorat** [ngrok/docker-ngrok#9]
Based on https://docs.docker.com/network/host/, `--net=host` only works for linux hosts. The workaround for mac and windows users seems to be to use the hostname `host.docker.internal` which will resolve to the host IP. https://docs.docker.com/desktop/mac/networking/#use-cases-and-workarounds

Feedback from a support case is that we should add that note to the examples for new users.

**Comment by zach-sherman** [comment]
closed by ^
